<?php
    $divI="<div class='photo'>";
    $divF="</div>";
    $miembros=[];
    
    $miembros[0]=array("grupo"=>"grupo1",
    "sectionI"=>"<section>",
    "divI"=>$divI,
    "link1"=>"",
    "visible1"=>"visible1()",
    "visibleF1"=>"visibleF1()",
    "img1"=>"img/comite/AlejandraVidales.jpg",
    "nombre1"=>"Alejandra Vidales",
    "pId1"=>"p1",
    "divF"=>$divF,
    "link2"=>"",
    "visible2"=>"visible2()",
    "visibleF2"=>"visibleF2()",
    "img2"=>"img/comite/DavidBravo.jpg",
    "nombre2"=>"David Bravo",
    "pId2"=>"p2",
    "sectionF"=>"</section>");

    $miembros[1]=array("grupo"=>"grupo2",
    "sectionI"=>"<section>",
    "divI"=>$divI,
    "link1"=>"",
    "visible1"=>"visible3()",
    "visibleF1"=>"visibleF3()",
    "img1"=>"img/comite/FannyVillegas.jpg",
    "nombre1"=>"Fanny Villegas",
    "pId1"=>"p3",
    "divF"=>$divF,
    "link2"=>"",
    "visible2"=>"visible4()",
    "visibleF2"=>"visibleF4()",
    "img2"=>"img/comite/IsaacSan.jpg",
    "nombre2"=>"Isaac San",
    "pId2"=>"p4",
    "sectionF"=>"</section>");

    $miembros[2]=array("grupo"=>"grupo3",
    "sectionI"=>"<section>",
    "divI"=>$divI,
    "link1"=>"",
    "visible1"=>"visible5()",
    "visibleF1"=>"visibleF5()",
    "img1"=>"img/comite/JorgeTrujillo.jpg",
    "nombre1"=>"Jorge Trujillo",
    "pId1"=>"p5",
    "divF"=>$divF,
    "link2"=>"",
    "visible2"=>"visible6()",
    "visibleF2"=>"visibleF6()",
    "img2"=>"img/comite/MargotOzuna.jpg",
    "nombre2"=>"Margot Ozuna",
    "pId2"=>"p6",
    "sectionF"=>"</section>");

    $miembros[3]=array("grupo"=>"grupo4",
    "sectionI"=>"<section>",
    "divI"=>$divI,
    "link1"=>"",
    "visible1"=>"visible7()",
    "visibleF1"=>"visibleF7()",
    "img1"=>"img/comite/MiltonPonce.jpg",
    "nombre1"=>"Milton Ponce",
    "pId1"=>"p7",
    "divF"=>$divF,
    "link2"=>"",
    "visible2"=>"visible8()",
    "visibleF2"=>"visibleF8()",
    "img2"=>"img/comite/NancySalazar.jpg",
    "nombre2"=>"Nancy Salazar",
    "pId2"=>"p8",
    "sectionF"=>"</section>");

    $miembros[4]=array("grupo"=>"grupo5",
    "sectionI"=>"<section>",
    "divI"=>$divI,
    "link1"=>"",
    "visible1"=>"visible9()",
    "visibleF1"=>"visibleF9()",
    "img1"=>"img/comite/OsmaryGarnica.jpg",
    "nombre1"=>"Osmary Garnica",
    "pId1"=>"p9",
    "divF"=>$divF,
    "link2"=>"",
    "visible2"=>"visible10()",
    "visibleF2"=>"visibleF10()",
    "img2"=>"img/comite/WendyAranda.jpg",
    "nombre2"=>"Wendy Aranda",
    "pId2"=>"p10",
    "sectionF"=>"</section>");

?>